cart-- MySQL Script generated by MySQL Workbench
-- Sun Mar  7 23:02:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_red-hot-chili-guitars
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_red-hot-chili-guitars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_red-hot-chili-guitars` DEFAULT CHARACTER SET utf8 ;
USE `db_red-hot-chili-guitars` ;

-- -----------------------------------------------------
-- Table `db_red-hot-chili-guitars`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_red-hot-chili-guitars`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `dni` INT NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `rol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_red-hot-chili-guitars`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_red-hot-chili-guitars`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_red-hot-chili-guitars`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_red-hot-chili-guitars`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instrument` VARCHAR(100) NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `mark` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  `color` VARCHAR(100) NOT NULL,
  `price` INT NOT NULL,
  `img` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1200) NOT NULL,
  `id_category` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_categories_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`id_category`)
    REFERENCES `db_red-hot-chili-guitars`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_red-hot-chili-guitars`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_red-hot-chili-guitars`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_product` INT NOT NULL,
  `id_user` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_users_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_cart_products_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `fk_cart_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_red-hot-chili-guitars`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_products`
    FOREIGN KEY (`id_product`)
    REFERENCES `db_red-hot-chili-guitars`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
